// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var frame_id, location, rdio;
    location = window.location.href;
    frame_id = parseInt(location[location.length - 1], 10);
    rdio = null;
    return window.parent.addEventListener("message", (function(m) {
      if (m.data.frame === frame_id) {
        console.log("Frame" + frame_id + ":", m.data);
        if (m.data.cmd === 'init') {
          rdio = $('#api').rdio(m.data.token);
          window.rdio = rdio;
        }
        if (m.data.cmd === 'play') {
          rdio.play(m.data.song);
          return 1;
        }
      }
    }), false);
  });

}).call(this);
