// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var tokens;
    tokens = ['GAlUSoJ1_____3h4NWV0bXZiNThiNDRqOGVmOXQ3cG4zdWxvY2FsaG9zdB-2VUCIzGZncDDMBuh5McM=', 'GAlUSoMQ_____3h4NWV0bXZiNThiNDRqOGVmOXQ3cG4zdWxvY2FsaG9zdDuEjVTHMn5bov7jS5g0kpg='];
    window.postMessage({
      frame: 1,
      cmd: 'init',
      token: tokens[0]
    }, '*');
    return window.postMessage({
      frame: 2,
      cmd: 'init',
      token: tokens[1]
    }, '*');
  });

}).call(this);
